import { Hono } from "hono";
import { trimTrailingSlash } from "hono/trailing-slash";
import accounts from "./accounts";
import auth from "./auth";
import backup from "./backup";
import bookmarks from "./bookmarks";
import compose from "./compose";
import emojis from "./emojis";
import federation from "./federation";
import home from "./home";
import login from "./login";
import logout from "./logout";
import notifications from "./notifications";
import profile from "./profile";
import settings from "./settings";
import setup from "./setup";
import social from "./social";
import tags from "./tags";
import webhookPages from "./webhooks";

const page = new Hono();

page.use(trimTrailingSlash());
page.route("/", home);
page.route("/:handle{@[^/]+}", profile);
page.route("/login", login);
page.route("/logout", logout);
page.route("/settings", settings);
page.route("/setup", setup);
page.route("/auth", auth);
page.route("/accounts", accounts);
page.route("/backup", backup);
page.route("/bookmarks", bookmarks);
page.route("/compose", compose);
page.route("/emojis", emojis);
page.route("/federation", federation);
page.route("/notifications", notifications);
page.route("/social", social);
page.route("/tags", tags);
page.route("/webhooks", webhookPages);

export default page;
